{% set name = "zipp" %}
{% set version = "3.20.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bc9eb26f4506fda01b81bcde0ca78103b6e62f991b381fec825435c836edbc29

build:
  number: 0
  skip: True  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm
    - wheel
    - toml
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - zipp
  requires:
    - pytest >=6,!=8.1.*
    - pip
    - jaraco.itertools
    - jaraco.test
    - func_timeout
    - jaraco.functools
    - more-itertools
    - importlib_resources  # [py<39]
  commands:
    - pip check
    - pytest tests

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  description: |
    Backport of pathlib-compatible object wrapper for zip files
  doc_url: https://zipp.readthedocs.io/
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
