{% set name = "zipp" %}
{% set version = "3.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a7a22e05929290a67401440b39690ae6563279bced5f314609d9d03798f56766

build:
  number: 0
  skip: True  # [py<37]
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
    # Add upper bound to get around circular dependency
    # zipp->setuptools_scm->importlib_metadata->zipp,
    # see https://github.com/conda-forge/zipp-feedstock/commit/94b9a99af3adb8060fb705cefe27f851028f9b9a
    - setuptools_scm >=3.4.1,<7
    - toml
  run:
    - python

test:
  source_files:
    - tests
  imports:
    - zipp
  requires:
    - pip
    - pytest >= 6
    # this is a downstream that has a version requirement on zipp
    - importlib_metadata
    - jaraco.itertools
    - func_timeout
    - jaraco.functools
    - more-itertools
  commands:
    - pip check
    - python -m unittest tests/test_zipp.py

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  description: |
    Backport of pathlib-compatible object wrapper for zip files
  doc_url: https://zipp.readthedocs.io/
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
