{% set name = "zipp" %}
{% set version = "3.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a07157588a12518c9d4034df3fbbee09c814741a33ff63c05fa29d26a2404166

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools_scm >=3.4.1
    - toml
    - setuptools-scm >=3.4.1
    - coherent.licensed
  run:
    - python
  run_constrained:
    - pytest-checkdocs >=2.4
    - pytest-enabler >=2.2

test:
  source_files:
    - tests
  imports:
    - zipp
  requires:
    - pytest >=6,!=8.1.*
    - pip
    - jaraco.itertools  # [py<313]
    - jaraco.test  # [py<313]
    - func_timeout
    - jaraco.functools  # [py<313]
    - more-itertools
    - importlib_resources  # [py<39]
  commands:
    - pip check
    # temporarily disabling tests for py313 until test dependencies are built.
    - pytest tests  # [py<313]

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  description: |
    Backport of pathlib-compatible object wrapper for zip files
  doc_url: https://zipp.readthedocs.io/
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
