{% set name = "zipp" %}
{% set version = "3.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a07157588a12518c9d4034df3fbbee09c814741a33ff63c05fa29d26a2404166

build:
  number: 0
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=3.4.1
    - toml
    # - coherent.licensed
  run:
    - python


test:
  source_files:
    - tests
  imports:
    - zipp
  requires:
    - pip
    - pytest >=6,!=8.1.*
    - jaraco.itertools 
    - jaraco.test
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest -v tests

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  description: |
    Backport of pathlib-compatible object wrapper for zip files
  doc_url: https://zipp.readthedocs.io
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
