{% set name = "zipp" %}
{% set version = "2.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: feae2f18633c32fc71f2de629bfb3bd3c9325cd4419642b1f1da42ee488d9b98
  patches:
    # See https://github.com/jaraco/zipp/pull/30
    - use-scm-version.patch

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools_scm >=3.4
  run:
    - python >=3.6
    - more-itertools

test:
  source_files:
    - test_zipp.py
  requires:
    - pip
    # this is a downstream that has a version requirement on zipp
    - importlib_metadata
  imports:
    - zipp
  requires:
    - pip
  commands:
    - python -m unittest test_zipp.py
    - pip check

about:
  home: https://github.com/jaraco/zipp
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A pathlib-compatible Zipfile object wrapper
  doc_url: https://zipp.readthedocs.io/en/latest
  dev_url: https://github.com/jaraco/zipp

extra:
  recipe-maintainers:
    - nehaljwani
