travis:
  secure:
    BINSTAR_TOKEN: DLSEvJQaC0FHy9lC6pIvbvhAwTKU0USmSL1TIlV7Tceo+hkxBrNvJkNlnBuqJ2aKv1Zd0t4KDpcCirhlsBHMWTTeSUmyTqQcbXninQCDnOiGrggeuucQR2bTnI/HMZWPlJ2XnVOxqHVLXF32WEv83n3ycmn1f1xeEZA+F23pOeBjkFQMCav/lJOCJTEXuz19glD5xkNTjtVsMzPas5JJvnV9QJ7lXigtbOKXLUig1eOnr2EN7UONmdnUimfwjUNSjX3Szpu7ukBZHlsqBG43mOSjq86tOboX4p+GQV1I+K+VkwePVlcHXZJYBt96EL3aJgDqPWw7B3+OCLmVcYPapb0dSbZRDNt0G03HoNubpoMqSAEyQCAT4d7U1sxLHwN86WZjBLGu2yFsca2fli6KYQ1DNeVP3DOGVA225Q4vOhnPvcuvP97ijYs0g9IL7WI/ZXMU4/YNoiH2wF6SiQvxUUWLbS4jnlm6+VDVH4LgXehw+1MvRFT9BAISanUGGcBZ3Q479VMmRS25rgM62UDhDgzeGnC5/4NVHcfS4PTMjzJKz9Y0VDFqL3TuAqCnpa5MLFTBOsAejR869n7tkFL9riB2R5ZkHj4zEhyxKXmPlhFtc0npInt5DxDZBpM1CC/3tbRFNOn8N+RGIoon9r8Ukdxx2lzKF/IRw7xyr00dRwg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
